### ISSUE TITLE
Draw Dilemma

### ISSUE THREAD

**Issue by heathersansone** [heatherkemp/heatherkemp.github.io#3]
I am stuck on how to structure the ability for the program to determine a draw or tie, so that the game can end and a new one can be started.  I have an else statement at the end of the determineWinner function that I decided to add a counter because it is looping.  Then I tried to create a function that when the drawCounter was equal to 9 to pop up an alert that the game was tied.  
The problem seems like a scope issue as I am having trouble getting the final count out of the determineWinner function and into the callDraw function.

When I created a new variable with the result of determineWinner it automatically upped the counter to 1.

**Comment by annarankin** [comment]
Hey Heather! Want to meet up for a few before lunch and look it over?

**Comment by heathersansone** [comment]
Definitely, thanks!

**Comment by annarankin** [comment]
Ok, I'll come find you
